################################################################################
#       Apache Guacamole Deployment with Ansible installation playbook         #
#       Maintainer: Majid Mortazavi                                            #
#       Douran Co. LTD                                                         #
#       Release note:                                                          #
#           - V.1.00  For Test                                                 #
#           - V.1.01  Add nexus                                                #
#           - V.1.02  Add py nexus                                             #
#           - V.2.00  Update jdk                                               #
#           - V.2.01  Update tomcat & JDK                                      #
################################################################################

---
- name: Deploy Guacamole
  hosts: guacamoleServers
  remote_user: root

  vars:
    nexus: "http://<NEXUS URL>/repository"
    apt_proxy: "/apt-proxy/"
    apt_hosted: "/apt-hosted/"
    nexus_components: "main restricted universe multiverse"
    tomcat_path: "<Tomcat_Path>"

  tasks:
    - name: Configure DNS resolvers
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        mode: "0644"
        content: |
          nameserver <DNS SERVER1>
          nameserver <DNS SERVER2>

    - name: Download Nexus APT public key from Nexus RAW repo
      ansible.builtin.get_url:
        url: "{{ nexus }}/raw-keys/root/gpg/apt/public.gpg.key"
        dest: "/PATH/TO/2/nexus-apt.asc"
        mode: "0644"

    - name: Dearmor Nexus APT key
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /PATH/TO/2/nexus-apt.gpg /PATH/TO/2/nexus-apt.asc"
      args:
        creates: "/PATH/TO/2/nexus-apt.gpg"

    - name: Add Nexus Repo to source.list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        mode: "0644"
        content: |
          deb [trusted=yes] {{ nexus }}{{ apt_proxy }} jammy {{ nexus_components }}
          deb [trusted=yes] {{ nexus }}{{ apt_proxy }} jammy-updates {{ nexus_components }}
          deb [trusted=yes] {{ nexus }}{{ apt_proxy }} jammy-security {{ nexus_components }}
          deb [trusted=yes] {{ nexus }}{{ apt_proxy }} jammy-backports {{ nexus_components }}
          deb [signed-by=/PATH/TO/2/nexus-apt.gpg] {{ nexus }}{{ apt_hosted }} jammy main

    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Apt upgrade tzdata package
      ansible.builtin.apt:
        name: tzdata
        state: latest

    - name: Set time and date
      community.general.timezone:
        name: Asia/Tehran

    - name:  Update apt repo and Install prerequisites
      ansible.builtin.apt:
        pkg:
        - gcc
        - nano
        - vim
        - curl
        - wget
        - g++
        - libcairo2-dev
        - libjpeg-turbo8-dev
        - libpng-dev
        - libtool-bin
        - libossp-uuid-dev
        - libavcodec-dev
        - libavformat-dev
        - libavutil-dev
        - libswscale-dev
        - build-essential
        - libpango1.0-dev
        - libssh2-1-dev
        - libssh2-1
        - libvncserver-dev
        - libtelnet-dev
        - libpulse-dev
        - libvorbis-dev
        - libwebp-dev
        - mysql-server
        - freerdp2-dev
        - freerdp2-x11
        - openjdk-17-jdk
        - python3-pip
        - libmysqlclient21
        - libzip-dev
        - libtesseract4
        - libopencv-videoio4.5d
        - libopencv-video4.5d
        - tesseract-ocr
        - tesseract-ocr-eng
        - tesseract-ocr-fas
        - zip
        - python3-lxml
        - linux-image-5.15.0-179-generic            ##Added because thease are not in ubuntu repositories.
        - linux-modules-5.15.0-179-generic          ##So I add them in the Nexus apt-hosted repo.
        - linux-modules-extra-5.15.0-179-generic
        - linux-headers-5.15.0-179
        - linux-headers-5.15.0-179-generic

        update_cache: yes

    - name: Configure pip to use Nexus (system-wide)
      ansible.builtin.copy:
        dest: /etc/pip.conf
        mode: "0644"
        content: |
          [global]
          index-url = http://<NEXUS URL>/repository/pypi-proxy/simple
          trusted-host = <NEXUS URL>
          timeout = 60

    - name: PIP3 install PyMySQL
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3
      tags:
        - prerequisites

    - name: Create tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: no
        shell: /usr/sbin/nologin

    - name: Create tomcat-9 directory
      file:
        path: "/opt/tomcat/"
        state: directory
        owner: tomcat
        group: tomcat

    - name: Download tomcat-9 tar.gz file
      ansible.builtin.unarchive:
        src: http://<NEXUS URL>/repository/apache-tomcat-9.0.118.tar.gz
        dest: /opt/tomcat/
        remote_src: yes

    - name: Change owner of tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat/
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat

    - name: Create Default config file for tomcat
      ansible.builtin.copy:
        content: |
                  JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                  CATALINA_HOME={{ tomcat_path }}
                  CATALINA_BASE={{ tomcat_path }}
                  CATALINA_OPTS="-Xms512M -Xmx8192M"
                  GUACAMOLE_HOME=/etc/guacamole
        dest: /etc/default/tomcat

    - name: Create service for tomcat
      ansible.builtin.copy:
        content: |
                  [Unit]
                  Description=Apache Tomcat 9
                  After=network.target

                  [Service]
                  Type=forking
                  EnvironmentFile=/etc/default/tomcat
                  User=tomcat
                  Group=tomcat
                  ExecStart={{ tomcat_path }}/bin/startup.sh
                  ExecStop={{ tomcat_path }}/bin/shutdown.sh
                  SuccessExitStatus=143
                  Restart=on-failure
                  RestartSec=10

                  [Install]
                  WantedBy=multi-user.target

        dest: /etc/systemd/system/tomcat9.service

    - name: Open port 8080 for guacamole
      community.general.ufw:
        rule: allow
        port: 8080
        proto: tcp

    - name: Check if ErrorReportValve exists
      community.general.xml:
        path: {{ tomcat_path }}/conf/server.xml
        xpath: /Server/Service/Engine/Host/Valve[@className="org.apache.catalina.valves.ErrorReportValve"]
        count: yes
      register: valve_check

    - name: Ensure ErrorReportValve exists
      community.general.xml:
        path: {{ tomcat_path }}/conf/server.xml
        xpath: /Server/Service/Engine/Host
        add_children:
          - Valve:
              className: "org.apache.catalina.valves.ErrorReportValve"
              showReport: "false"
              showServerInfo: "false"
      when: valve_check.count == 0

    - name: Download and unarchive guacamole server
      ansible.builtin.unarchive:
        src: ./guacamole-server-1.5.5.tar.gz
        dest: /root/

    - name: Configure command for Guacamole server
      ansible.builtin.shell:
        chdir: /root/guacamole-server-1.5.5
        cmd: ./configure --with-init-dir=/etc/init.d

    - name: Make command for Guacamole server
      community.general.make:
        chdir: /root/guacamole-server-1.5.5

    - name: Make Install command for Guacamole server
      community.general.make:
        chdir: /root/guacamole-server-1.5.5
        target: install

    - name: ldconfig command for Guacamole server
      ansible.builtin.shell:
        chdir: /root/guacamole-server-1.5.5
        cmd: ldconfig

    - name: Make directories (extensions,lib)
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/guacamole/
        - /etc/guacamole/extensions
        - /etc/guacamole/lib

    - name: Create file guacd.conf
      ansible.builtin.copy:
        src: ./guacd.conf
        dest: /etc/guacamole/guacd.conf
        follow: yes

    - name: Remove ROOT dir of tomcat
      file:
        path: {{ tomcat_path }}/webapps/ROOT
        state: absent

    - name: Install Guacamole client
      ansible.builtin.copy:
        src: ./guacamole-1.5.5.war
        dest: {{ tomcat_path }}/webapps/ROOT.war
        follow: yes

    - name: Guacamole service enable and restart
      ansible.builtin.service:
        name: guacd
        enabled: yes
        state: started

    - name: Config Guacamole Server
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - echo "GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/default/tomcat
        - echo "export GUACAMOLE_HOME=/etc/guacamole" | sudo tee -a /etc/profile

    - name: Create file guacamole.properties
      ansible.builtin.copy:
        src: ./guacamole.properties
        dest: /etc/guacamole/guacamole.properties

    - name: Enable mysql service
      ansible.builtin.service:
        name: mysql
        enabled: yes
        state: started

    - name: MySQL Connector
      ansible.builtin.copy:
        src: ./mysql-connector-j-8.3.0.jar
        dest: /etc/guacamole/lib/

    - name: JDBC Auth must download and install
      ansible.builtin.copy:
        src: ./guacamole-auth-jdbc-mysql-1.5.3.jar
        dest: /etc/guacamole/extensions/

    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes

    - name: Create Database
      mysql_db:
        name: <MySQL_DB>
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create Database user
      mysql_user:
        name: <MySQL_USER>
        password: <MySQL_USER_PASS>
        priv: '*.*:ALL'
        host: '%'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Copy the create tables query files
      ansible.builtin.copy:
        src: ./guacamole-auth-jdbc-1.5.5/mysql/schema/001-create-schema.sql
        dest: /etc/guacamole/extensions/

    - name: Copy the create tables query files
      ansible.builtin.copy:
        src: ./guacamole-auth-jdbc-1.5.5/mysql/schema/002-create-admin-user.sql
        dest: /etc/guacamole/extensions/

    - name: Create Guacamole tables
      mysql_db:
        name: <MySQL_DB>
        target: /etc/guacamole/extensions/001-create-schema.sql
        state: import
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create Guacamole tables 2
      mysql_db:
        name: <MySQL_DB>
        target: /etc/guacamole/extensions/002-create-admin-user.sql
        state: import
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Restart tomcat service
      ansible.builtin.service:
        name: tomcat9
        enabled: yes
        state: restarted

    - name: Reboot server to apply kernel update
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible to apply kernel update."
